# Generated by Django 3.1.5 on 2021-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backened', '0002_auto_20210225_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='font_size',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
